version: '3.7'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass-itic8
      MYSQL_DATABASE: itic_database
      MYSQL_USER: itic
      MYSQL_PASSWORD: pass-itic8assword 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass-itic8

volumes:
  db_data:
